#!/bin/dash
for s; do
  if [ -d "$s" ]; then
    dolphin "$s" &
    continue
  fi
  case "$s" in
    *.html)
      google-chrome "$s";;
    *.zip)
      unzip -d "$(basename "$s" .zip)" "$s";;
    *)
      xdg-open "$@";;
  esac
done
