#!/bin/dash
for s; do
  if [ -d "$s" ]; then
    dolphin "$s" &
    continue
  fi
  case "$s" in
    *.html)
      google-chrome "$s";;
    *.zip)
      unzip -d "$(basename "$s" .zip)" "$s";;
    *.png|*.jpg|*.jpeg|*.jfif|*.gif)
      gwenview "$s" &;;
    *.pdf)
      okular "$s" &;;
    *.md)
      mdview "$s";;
    *)
      xdg-open "$@";;
  esac
done
