#!/bin/bash
# Start minidlnas with config names matching pattern
# pattern is a grep -P regex
DRY="${DRY-no}"
cd ~/.minidlna/$USER

go() {
  if [ -z "$1" ]; then P=.; else P="$1"; fi
  ls -1d */ | cut -f1 -d/ | grep -q -P "$P"
  if [ ! $? = 0 ]; then 
    echo "No matches for $1"; 
  else
    ls -1d */ | cut -f1 -d/ | grep "$P" | while read s; do
      if [ "$DRY" = y ]; then
        echo "Would start minidlna $s"
      else
        echo "Starting minidlna $s"
        minif "$s"
      fi
    done
  fi
}
for s; do go "$s"; done
