#!/bin/bash

# Given a minidlna.conf or a directory containing such
# launches minidlna with that config

f="$(readlink -f "$1")"
if [ -d "$f" ]; then
  d="$f"
  a=minidlna.conf
elif [ -f "$f" ]; then
  d="$(dirname "$f")"
  a="$(basename "$f")"
else
  echo "$1 is not a valid minidlnad config file (or folder containing minidlna.conf"
  exit 1
fi
if [ -d "$d" ]; then
  cd "$d"
  if [ -e "$d/pid" ]; then
    echo "$d/pid exists"
    pid="$(<$d/pid)"
    if [ -d "/proc/$pid" ]; then
      echo "minidlna $f already running"
      exit 0
    fi
  fi
  if [ -f "$a" ]; then
    /usr/sbin/minidlnad -f "$a" -P "$PWD"/pid
  fi
fi
