#!/usr/bin/python
import socket
import sys
def send_message(host,port,message):
  with socket.socket(socket.AF_INET,socket.SOCK_DGRAM) as s:
    s.connect((host,port))
    s.send(message)
d = {
  ".": "localhost",
  "t": "t470s1",
  "f2": "frodo2",
  "f3": "frodo3",
  "b": "behemoth",
  "l": "l440a"
}
args = sys.argv[1:]
if len(args) > 0:
  if args[0] == "all":
    hosts = [x for x in d.values()]
  else:
    hosts = [d[x] if x in d else x for x in args[0].split("+")]
  t = "\n".join(args[1:]).rstrip()
else:
  hosts = ["t470s1"]
  t = ""
if not sys.stdin.isatty():
  t += "\n"+sys.stdin.read().rstrip()
print(f"Sending: {t}")
for host in hosts:
  send_message(host,2708,t.encode())
