#!/bin/bash
export SCHEMA='$I$S'
export PGEN_LENGTH=16
j() {
  local S="$SECRET" I="$1"
  export S I
  local INP="$(eval echo $SCHEMA)"
  echo "$INP" | md5sum | base64 | cut -c1-$PGEN_LENGTH
}
jj() {
  local S="$SECRET" I="$1"
  local INP="$(eval echo $SCHEMA)"
  echo -n "$INP" | sha256sum | cut -c1-64 | xxd -r -p | base64 | tr '/+' '#@' | cut -c1-$PGEN_LENGTH
}
jjp() {
  echo -n "$(jj "$@")" | tee /dev/clipboard
  echo
}
echo "use jjp <input> to copy to clipboard (jj <input> | pc does not work)"
s() {
  echo -n "Secret: "
  read -s SECRET
  echo
  echo -n "MD5: "
  j MrFlibble | cut -c1-4
  echo -n "SHA256: "
  jj MrFlibble | cut -c1-4
}
l() {
  local A="$1" B
  if [ -z "$A" ]; then
    echo "Length: $PGEN_LENGTH"
    return
  fi
  ((B=A+0))
  if ((B < 4 )); then
    echo "Length too short ($A==$B<4)"
  else
    PGEN_LENGTH="$B"
  fi
}
p() {
  pgen "$@"
}
export -f j jj s l p jjp
export SECRET PS1="jj> "
s
bash --norc --noprofile

